CREATE TABLE USER(
   Id_USER INT AUTO_INCREMENT,
   last_name VARCHAR(50) ,
   first_name VARCHAR(50) ,
   email VARCHAR(100) ,
   password VARCHAR(255) ,
   phone VARCHAR(20) ,
   registration_date DATETIME,
   PRIMARY KEY(Id_USER),
   UNIQUE(email)
);

CREATE TABLE NOTEBOOK(
   Id_NOTEBOOK INT AUTO_INCREMENT,
   pdf_file TEXT,
   upload_date DATETIME,
   PRIMARY KEY(Id_NOTEBOOK)
);

CREATE TABLE DESTINATION(
   Id_DESTINATION INT AUTO_INCREMENT,
   name VARCHAR(100) ,
   country VARCHAR(100) ,
   description TEXT,
   pexels_keyword VARCHAR(100) ,
   slug VARCHAR(50) ,
   PRIMARY KEY(Id_DESTINATION)
);

CREATE TABLE CATEGORY(
   Id_CATEGORY INT AUTO_INCREMENT,
   name ENUM('destination','conseils','actualites','informations','experiences'),
   slug VARCHAR(80) ,
   PRIMARY KEY(Id_CATEGORY)
);

CREATE TABLE ADMIN(
   Id_ADMIN INT AUTO_INCREMENT,
   email VARCHAR(100) ,
   password VARCHAR(255) ,
   last_login DATETIME,
   PRIMARY KEY(Id_ADMIN),
   UNIQUE(email)
);

CREATE TABLE MEDIA(
   Id_MEDIA INT AUTO_INCREMENT,
   file_name VARCHAR(255) ,
   upload_date DATETIME,
   caption TEXT,
   copyright VARCHAR(150) ,
   PRIMARY KEY(Id_MEDIA)
);

CREATE TABLE MESSAGE(
   Id_MESSAGE INT AUTO_INCREMENT,
   name VARCHAR(100) ,
   email VARCHAR(100)  NOT NULL,
   phone VARCHAR(20) ,
   message TEXT,
   status ENUM ('non_lu','lu', 'repondu'),
   sent_date DATETIME,
   Id_ADMIN INT,
   PRIMARY KEY(Id_MESSAGE),
   FOREIGN KEY(Id_ADMIN) REFERENCES ADMIN(Id_ADMIN)
);

CREATE TABLE TRAVEL_PROJECT(
   Id_TRAVEL_PROJECT INT AUTO_INCREMENT,
   title VARCHAR(150) ,
   destination VARCHAR(255) ,
   start_date DATETIME,
   end_date DATETIME,
   budget DECIMAL(10,2)  ,
   status ENUM('en_attente','en_cours','confirme','termine'),
   notes TEXT,
   Id_NOTEBOOK INT NOT NULL,
   Id_USER INT NOT NULL,
   PRIMARY KEY(Id_TRAVEL_PROJECT),
   UNIQUE(Id_NOTEBOOK),
   FOREIGN KEY(Id_NOTEBOOK) REFERENCES NOTEBOOK(Id_NOTEBOOK),
   FOREIGN KEY(Id_USER) REFERENCES USER(Id_USER)
);

CREATE TABLE ARTICLE(
   Id_ARTICLE INT AUTO_INCREMENT,
   title VARCHAR(200) ,
   content TEXT,
   status ENUM('brouillon','publie'),
   publication_date DATETIME,
   slug VARCHAR(200) ,
   Id_MEDIA INT,
   Id_ADMIN INT NOT NULL,
   Id_DESTINATION INT,
   PRIMARY KEY(Id_ARTICLE),
   FOREIGN KEY(Id_MEDIA) REFERENCES MEDIA(Id_MEDIA),
   FOREIGN KEY(Id_ADMIN) REFERENCES ADMIN(Id_ADMIN),
   FOREIGN KEY(Id_DESTINATION) REFERENCES DESTINATION(Id_DESTINATION)
);

CREATE TABLE TYPE(
   Id_TYPE INT AUTO_INCREMENT,
   title VARCHAR(200) ,
   description TEXT,
   slug VARCHAR(50) ,
   Id_MEDIA INT NOT NULL,
   PRIMARY KEY(Id_TYPE),
   UNIQUE(Id_MEDIA),
   FOREIGN KEY(Id_MEDIA) REFERENCES MEDIA(Id_MEDIA)
);

CREATE TABLE DOCUMENT(
   Id_DOCUMENT INT AUTO_INCREMENT,
   type ENUM('devis','facture','autre'),
   pdf_file VARCHAR(255) ,
   status ENUM('en_attente','valide','refuse'),
   upload_date DATETIME,
   Id_TRAVEL_PROJECT INT NOT NULL,
   PRIMARY KEY(Id_DOCUMENT),
   FOREIGN KEY(Id_TRAVEL_PROJECT) REFERENCES TRAVEL_PROJECT(Id_TRAVEL_PROJECT)
);

CREATE TABLE BELONGS_TO(
   Id_CATEGORY INT,
   Id_ARTICLE INT,
   PRIMARY KEY(Id_CATEGORY, Id_ARTICLE),
   FOREIGN KEY(Id_CATEGORY) REFERENCES CATEGORY(Id_CATEGORY),
   FOREIGN KEY(Id_ARTICLE) REFERENCES ARTICLE(Id_ARTICLE)
);

CREATE TABLE CONTAINS_CONTENTS(
   Id_ARTICLE INT,
   Id_MEDIA INT,
   PRIMARY KEY(Id_ARTICLE, Id_MEDIA),
   FOREIGN KEY(Id_ARTICLE) REFERENCES ARTICLE(Id_ARTICLE),
   FOREIGN KEY(Id_MEDIA) REFERENCES MEDIA(Id_MEDIA)
);
